set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1)
cmake_minimum_required(VERSION 3.17)

set(EMBY_STM32xx_FREERTOS_PLATFORM ${CMAKE_CURRENT_LIST_DIR})
message(STATUS "Adding Platform from: " ${EMBY_STM32xx_FREERTOS_PLATFORM})

set(STM32XX_BAREMETAL_DIR ${EMBY_STM32xx_FREERTOS_PLATFORM}/../STM32xx_Baremetal)
# resolve to absolute path to avoid empty expansion and include issues
get_filename_component(STM32XX_BAREMETAL_DIR "${STM32XX_BAREMETAL_DIR}" REALPATH)
# import before baremetal to setup toolchain

include(${STM32XX_BAREMETAL_DIR}/emby-platform.cmake)
include("${EMBY_STM32xx_FREERTOS_PLATFORM}/../RTOS/FreeRTOS/freertos-kernel.cmake")

#include RTOS WRAPPER FOR EMBY
include_directories(${EMBY_STM32xx_FREERTOS_PLATFORM}/EmbyThreading)
include_directories(${EMBY_STM32xx_FREERTOS_PLATFORM}/EmbySystem)

#remove this files includes before
EMBY_UTILS_REMOVE_FILES_FROM_LIST_WITH_WILDCARD("${STM32XX_BAREMETAL_DIR}/EmbyThreading/*.cc" SOURCES)
EMBY_UTILS_REMOVE_FILES_FROM_LIST_WITH_WILDCARD("${STM32XX_BAREMETAL_DIR}/EmbySystem/System.cc" SOURCES)

#remove include dirs as well
EMBY_UTILS_REMOVE_DIRS_FROM_INCLUDE(${STM32XX_BAREMETAL_DIR}/EmbyThreading)

message(STATUS "DEBUG: EMBY_STM32xx_FREERTOS_PLATFORM='${EMBY_STM32xx_FREERTOS_PLATFORM}'")
message(STATUS "DEBUG: STM32XX_BAREMETAL_DIR='${STM32XX_BAREMETAL_DIR}'")

EMBY_UTILS_CHANGE_IMPL_INCLUDE_FROM_EMBY_ROOT(${EMBY_STM32xx_FREERTOS_PLATFORM} "${STM32XX_BAREMETAL_DIR}")

EMBY_UTILS_INCLUDE_ONLY_IMPL_DIRS(${EMBY_STM32xx_FREERTOS_PLATFORM} TRUE)



file(GLOB_RECURSE EMBY_FREERTOS_SOURCES
        ${EMBY_STM32xx_FREERTOS_PLATFORM}/EmbyThreading/*.cc
        ${EMBY_STM32xx_FREERTOS_PLATFORM}/EmbySystem/*.cc
)



list(APPEND SOURCES ${EMBY_FREERTOS_SOURCES})

#EMBY_UTILS_PRINT_GLOBAL_IMPL_INCLUDES()
